services:
  database:
    build: ./database
    restart: always
    volumes:
      - bustijdenapi_dbdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_DB: gtfs
      POSTGRES_USER: gtfs
      POSTGRES_PASSWORD: gtfsgtfs
  redis:
    image: redis:7.4-bookworm
    hostname: redis
    restart: always
  api:
    build: ./api
    hostname: api
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://gtfs:gtfsgtfs@database:5432/gtfs
      REDIS_URL: redis://redis:6379
      USER_AGENT: BUSTIJDEN-HAS/1.0 (app@remcokersten.nl)
    depends_on:
      - database
      - redis

networks:
  default:
    name: bustijdenapi
volumes:
  bustijdenapi_dbdata:
