services:
  database:
    image: postgres:16-trixie
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ${PWD}/scripts/importstaticdata.sh:/opt/importstaticdata.sh:ro
    environment:
      POSTGRES_DB: gtfs
      POSTGRES_USER: gtfs
      POSTGRES_PASSWORD: gtfsgtfs
  redis:
    image: redis:7-alpine
    restart: always
  bustijden:
    image: bustijdenapi:0.9.1
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://gtfs:gtfsgtfs@database:5432/gtfs
      REDIS_URL: redis://redis:6379
      USER_AGENT: BUSTIJDEN-HAS/1.0 (app@remcokersten.nl)
    depends_on:
      - database
      - redis

volumes:
  dbdata:
